//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class insurance_calc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public insurance_calc()
        {
            this.insurance = new HashSet<insurance>();
        }
    
        public int id { get; set; }
        public string tb { get; set; }
        public string kt { get; set; }
        public string kbm { get; set; }
        public string kvs { get; set; }
        public string ko { get; set; }
        public string km { get; set; }
        public string ks { get; set; }
        public string total { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<insurance> insurance { get; set; }
    }
}
